name: Build
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Build
        run: ./gradlew clean build
